### ISSUE TITLE
Bonjour support

### ISSUE THREAD

**Issue by MegaZeroX10** [kenyapcomau/p910nd#1]
Does it support broadcasting the connected printer via Bonjour? If not, then it should be added.

**Comment by MegaZeroX10** [comment]
Or you can tell me how to use something else to broadcast it via Bonjour.

**Comment by kenyapcomau** [comment]
No facility for that. If somebody want to submit patches or a how to for doing this, feel free. I have no idea how.

**Comment by MegaZeroX10** [comment]
You just need to have it broadcast the printer via mDNS.

**Comment by MegaZeroX10** [comment]
Maybe you could try integrating it into https://github.com/troglobit/mdnsd (or tell me how to make a .service file that broadcasts it).

**Comment by MegaZeroX10** [comment]
I tried using it. I managed to get the Raspberry Pi to show up as "raspberrypi" when searching for Printers via Bonjour on a Macbook Pro. The issue now is that when I try to add the printer, I get a message stating that it ran into an error while trying to add the device.

**Comment by asparatu** [comment]
Hello @MegaZeroX10 
By default, RPi has avahi-daemon installed, which does mDNS, which is [Apple's Zeroconf](https://linux.die.net/man/8/avahi-daemon) (Bonjour) daemon. So, you do not need to install mdnsd on the RPi. Just look in the /etc directory and you should see avahi service. If that is not installed just do **sudo apt install avahi-daemon**.  

Try using the avahi-daemon, it might fix your issue. I know when was trying to get p910nd to work on a Macbook Pro, it was having an issue with connecting to the printer. I just end up using the Cups installation on the Rpi for the Macbook Pro, but that even had an issue working all the time.
