### ISSUE TITLE
How to setup to print port 9001 and 9002

### ISSUE THREAD

**Issue by asparatu** [kenyapcomau/p910nd#5]
Hello @kenyapcomau 

I don't really see any documentation on how to set up more than one printer with p910nd. Man Page says, 
Port 9100 is copied to /dev/lp0, 9101 to /dev/lp1 and 9102 to /dev/lp2. The default is port 9100 to /dev/lp0, but does not tell you how to do it. 

I see that there is p910nd_num, which I assume that you specify the port, but when added more than one set of variables does not work.

How would you do this?

my /etc/default/p910nd
  `Printer number, if not 0`
  `P910ND_NUM="`
 ` #Additional daemon arguments, see man 8 p910nd`
  `P910ND_OPTS="-f /dev/usb/lp0"`
  `# Debian specific (set to 1 to enable start by default)`
  `P910ND_START=1`

**Comment by kenyapcomau** [comment]
This is dependent on whether the package in your distribution (Debian) supports multiple instances of the service. I don't control that.
